print("Gautrav Lahoti B1 2501069")
JEE_STUDENTS = {'BOB','LAURA','MIKE','DONALD','HOPPER'}
NEET_STUDENTS = {'BOB','HENRY','MAX','WILL','STEVE'}
CET_STUDENTS = {'LAURA','HENRY','JOYCE','DUSTIN','MIKE'}
print("The Original JEE STUDENTS ",JEE_STUDENTS)
print("The Original NEET STUDENTS ",NEET_STUDENTS)
print("The Original CET STUDENTS ",CET_STUDENTS)

ALL_STUDENTS = CET_STUDENTS | JEE_STUDENTS | NEET_STUDENTS
print("Total Students",ALL_STUDENTS)

COMMON_STUDENTS = CET_STUDENTS & JEE_STUDENTS & NEET_STUDENTS
print("Common Students",COMMON_STUDENTS)

CET_JEE = CET_STUDENTS & JEE_STUDENTS
print("Common in CET and JEE",CET_JEE)

JEE_NOT_NEET = JEE_STUDENTS - NEET_STUDENTS
print("In JEE but not in NEET",JEE_NOT_NEET)

ONLY_CET = CET_STUDENTS - JEE_STUDENTS - NEET_STUDENTS
print("Only in CET",ONLY_CET)
